import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { GA_TRACKING_ID } from "./lib/gtag";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <script 
      async 
      src={'https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}'}
      ></script>
      <script id="google-analytics">
        {
          `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'GA_TRACKING_ID');
          `
        }
      </script>  


      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
